feat(schema.prisma): adding user model
es20231/eqp7 pull request #50
Opened 2023-07-14 16:01 UTC by JoseeAugusto

2023-07-14 17:44 UTC, CassianoJunior requested changes
Olha os comentários

2023-07-14 17:44 UTC, CassianoJunior commented on server/prisma/schema.prisma
> +  userName  String      @unique
acho que aqui nao precisa de cammelcase, deixa `username` msm

2023-07-14 19:03 UTC, CassianoJunior commented on server/prisma/schema.prisma
> +  id        String      @id @default(uuid())
Vamos usar a estratégia cuid() ao invés da uuid().

2023-07-14 21:24 UTC, JoseeAugusto commented on server/prisma/schema.prisma
> +  userName  String      @unique
tira só dessa linha ou de todas?

2023-07-15 01:55 UTC, CassianoJunior commented on server/prisma/schema.prisma
> +  userName  String      @unique
so ai mesmo, no username.

2023-07-15 14:17 UTC, JoseeAugusto commented
Mudanças feitas.

2023-07-16 00:23 UTC, CassianoJunior approved these changes
LGTM

2023-07-17 15:17 UTC, CassianoJunior requested changes
Cria outra branch com essas alterações, o PR só é relacionado ao modelo de usuário do prisma

2023-07-17 19:05 UTC, closed without merging