feat(server): add post endpoints
es20231/eqp7 pull request #55
Opened 2023-07-22 15:19 UTC by JoseeAugusto

# Contém:

Todo o necessário para implementar os endpoints para posts

- Repository com seus respectivos testes
- Service com seus respectivos testes
- Factory com seus respectivos testes
- Controller com testes manuais feitos no postman
- Routes com testes manuais feitos no postman

2023-07-22 16:01 UTC, CassianoJunior commented
Nessa mesma branch, faz o merge com a main atual, resolve os conflitos e faz o commit.

Que nem eu fiz nesse [commit](https://github.com/es20231/eqp7/commit/a5e068f8cce7aba88b64d07cf3641ba03dda58da)

2023-07-22 16:07 UTC, CassianoJunior requested changes
Comentei as mudanças pra tu fazer, dá uma olhada.

2023-07-22 16:39 UTC, EduardoRibeiroBR submitted a review, later dismissed

2023-07-22 16:48 UTC, assis23 approved these changes

2023-07-22 18:06 UTC, CassianoJunior commented
Percebi que o teu vscode não tá usando as configurações do eslint, e o código não tá mantendo o padrão. Veja isso também.

2023-07-23 20:03 UTC, JoseeAugusto commented
vou fechar esse pr e abrir outro, tive que mudar para outra branch

2023-07-23 20:03 UTC, closed without merging